import React from 'react';
import { useTranslation } from '../../lib/language';
import PublicFooter from '../../components/layout/PublicFooter';
import './LegalPages.css';

const PrivacyPolicy = () => {
  const { t, currentLanguage } = useTranslation();

  return (
    <div className="legal-page">
      <div className="legal-container">
        <header className="legal-header">
          <h1>
            {currentLanguage === 'rw' 
              ? 'Politiki y\'Ubwigenge' 
              : 'Privacy Policy'
            }
          </h1>
          <p className="legal-subtitle">
            {currentLanguage === 'rw' 
              ? 'Kuva ku wa 1 Mutarama 2024' 
              : 'Effective as of January 1, 2024'
            }
          </p>
        </header>

        <div className="legal-content">
          {/* Introduction */}
          <section className="legal-section">
            <h2>
              {currentLanguage === 'rw' 
                ? '1. Intangiriro' 
                : '1. Introduction'
              }
            </h2>
            <p>
              {currentLanguage === 'rw' 
                ? 'DigLearners ni ikigo cy\'uburezi bwo mu ikoranabuhanga cyashyizweho mu Rwanda. Tugamije kurengera ubwigenge bw\'abanyeshuri bacu, ababyeyi babo, n\'abarezi. Iyi politiki isobanura uko dukusanya, dukoresha, kandi dukinga amakuru y\'abantu.' 
                : 'DigLearners is an educational technology platform based in Rwanda, dedicated to enhancing digital literacy in primary schools. We are committed to protecting the privacy and safety of our students, their parents/guardians, and teachers. This Privacy Policy explains how we collect, use, and safeguard personal information.'
              }
            </p>
            <p>
              {currentLanguage === 'rw' 
                ? 'Mukoresha serivisi zacu, mwemera ko mwiyandikishije kandi mukemera politiki yacu y\'ubwigenge. Niba mutemera, nyamuneka mutazikoresha serivisi zacu.' 
                : 'By using our services, you acknowledge that you have read, understood, and agree to this Privacy Policy. If you do not agree with any part of this policy, please do not use our services.'
              }
            </p>
          </section>

          {/* Information We Collect */}
          <section className="legal-section">
            <h2>
              {currentLanguage === 'rw' 
                ? '2. Amakuru Dukusanya' 
                : '2. Information We Collect'
              }
            </h2>
            <p>
              {currentLanguage === 'rw' 
                ? 'Dukusanya amakuru y\'ibanze gusa kugira ngo dushobore guha serivisi z\'uburezi. Dukusanya amakuru atandukanye bitewe n\'urwego rw\'umukoresha:' 
                : 'We collect only the minimum information necessary to provide educational services. The type of information we collect varies depending on the user role:'
              }
            </p>
            
            <div className="legal-list">
              <h3>
                {currentLanguage === 'rw' 
                  ? 'Amakuru y\'Abanyeshuri:' 
                  : 'Student Information:'
                }
              </h3>
              <ul>
                <li>
                  {currentLanguage === 'rw' 
                    ? 'Amazina y\'umunyeshuri (amazina y\'ibanze n\'amazina y\'inyuma)' 
                    : 'Student name (first and last name)'
                  }
                </li>
                <li>
                  {currentLanguage === 'rw' 
                    ? 'Ubwoba bw\'umunyeshuri (kugira ngo dushobore guha ibyiciro by\'ibanze)' 
                    : 'Student age (to provide age-appropriate content)'
                  }
                </li>
                <li>
                  {currentLanguage === 'rw' 
                    ? 'Urwego rw\'ishuli (kugira ngo dushobore guha ibyiciro by\'ibanze)' 
                    : 'Grade level (to provide grade-appropriate content)'
                  }
                </li>
                <li>
                  {currentLanguage === 'rw' 
                    ? 'Kode y\'iyandikisha (yateguwe n\'umwarimu kugira ngo abanyeshuri bashobore kwinjira)' 
                    : 'Registration code (generated by teacher for student login)'
                  }
                </li>
                <li>
                  {currentLanguage === 'rw' 
                    ? 'Amakuru y\'ubukoresha (intambwe, amasomo yarangiye, amanota, ibyiciro by\'ibanze)' 
                    : 'Learning data (progress, completed lessons, scores, achievements)'
                  }
                </li>
                <li>
                  {currentLanguage === 'rw' 
                    ? 'Amakuru y\'ubukoresha (igihe cyose abanyeshuri bakoresha serivisi, ibyiciro by\'ibanze)' 
                    : 'Usage data (time spent on platform, features accessed)'
                  }
                </li>
              </ul>
            </div>

            <div className="legal-list">
              <h3>
                {currentLanguage === 'rw' 
                  ? 'Amakuru y\'Abarezi:' 
                  : 'Teacher Information:'
                }
              </h3>
              <ul>
                <li>
                  {currentLanguage === 'rw' 
                    ? 'Amazina y\'umwarimu' 
                    : 'Teacher full name'
                  }
                </li>
                <li>
                  {currentLanguage === 'rw' 
                    ? 'Imeli y\'umwarimu (kugira ngo dushobore guhagararira)' 
                    : 'Teacher email address (for communication)'
                  }
                </li>
                <li>
                  {currentLanguage === 'rw' 
                    ? 'Ijambo ry\'ibanga (ryakoreshwa mu nzira y\'ubwoba)' 
                    : 'Password (securely hashed and encrypted)'
                  }
                </li>
                <li>
                  {currentLanguage === 'rw' 
                    ? 'Amakuru y\'ishuli (ishuli abarezi bakorera)' 
                    : 'School information (school where teacher works)'
                  }
                </li>
                <li>
                  {currentLanguage === 'rw' 
                    ? 'Amakuru y\'ubukoresha (abanyeshuri barezi bakurikirana, amasomo yatanzwe)' 
                    : 'Teaching data (students managed, lessons assigned)'
                  }
                </li>
              </ul>
            </div>

            <div className="legal-list">
              <h3>
                {currentLanguage === 'rw' 
                  ? 'Amakuru y\'Ababyeyi:' 
                  : 'Parent/Guardian Information:'
                }
              </h3>
              <ul>
                <li>
                  {currentLanguage === 'rw' 
                    ? 'Amazina y\'umubyeyi cyangwa umurinzi' 
                    : 'Parent/guardian name'
                  }
                </li>
                <li>
                  {currentLanguage === 'rw' 
                    ? 'Imeli y\'umubyeyi (kugira ngo dushobore guhagararira ku makuru y\'umwana)' 
                    : 'Parent/guardian email (for progress updates)'
                  }
                </li>
                <li>
                  {currentLanguage === 'rw' 
                    ? 'Ihuza n\'umunyeshuri (ukuntu umubyeyi ahuza n\'umwana we)' 
                    : 'Relationship to student (how parent is connected to student)'
                  }
                </li>
              </ul>
            </div>

            <div className="legal-list">
              <h3>
                {currentLanguage === 'rw' 
                  ? 'Amakuru y\'Ubukoresha:' 
                  : 'Technical Information:'
                }
              </h3>
              <ul>
                <li>
                  {currentLanguage === 'rw' 
                    ? 'IP aderesi (kugira ngo dushobore gukoresha serivisi)' 
                    : 'IP address (for service functionality)'
                  }
                </li>
                <li>
                  {currentLanguage === 'rw' 
                    ? 'Ubwoba bw\'ikoresha (ubwoba bw\'ikoresha, ururimi)' 
                    : 'Device information (device type, language preferences)'
                  }
                </li>
                <li>
                  {currentLanguage === 'rw' 
                    ? 'Amakuki (amakuki y\'ibanze gusa kugira ngo serivisi zikore)' 
                    : 'Cookies (essential cookies only for platform functionality)'
                  }
                </li>
              </ul>
            </div>
          </section>

          {/* How We Use Information */}
          <section className="legal-section">
            <h2>
              {currentLanguage === 'rw' 
                ? '3. Uko Dukoresha Amakuru' 
                : '3. How We Use Information'
              }
            </h2>
            <p>
              {currentLanguage === 'rw' 
                ? 'Dukoresha amakuru yose y\'abantu gusa mu nzira y\'uburezi kandi dukoresha amakuru y\'abana gusa mu nzira y\'uburezi n\'ubwoba. Ntidukoresha amakuru y\'abana mu nzira y\'ubucuruzi.' 
                : 'We use all personal information solely for educational purposes and to improve our services. We use children\'s information only for educational purposes and safety. We never use children\'s information for commercial purposes.'
              }
            </p>
            
            <div className="legal-list">
              <h3>
                {currentLanguage === 'rw' 
                  ? 'Injiza z\'Uburezi:' 
                  : 'Educational Purposes:'
                }
              </h3>
              <ul>
                <li>
                  {currentLanguage === 'rw' 
                    ? 'Guhanga serivisi z\'uburezi zihuje n\'ubwoba bw\'abanyeshuri' 
                    : 'To provide personalized learning experiences tailored to each student'
                  }
                </li>
                <li>
                  {currentLanguage === 'rw' 
                    ? 'Gukurikira intambwe y\'abanyeshuri kandi guha inyigisho z\'ibanze' 
                    : 'To track student progress and provide appropriate feedback'
                  }
                </li>
                <li>
                  {currentLanguage === 'rw' 
                    ? 'Guhanga amasomo n\'ibyiciro by\'ibanze bitewe n\'urwego rw\'ishuli' 
                    : 'To deliver lessons and content appropriate for each grade level'
                  }
                </li>
                <li>
                  {currentLanguage === 'rw' 
                    ? 'Gufasha abarezi gukurikira intambwe y\'abanyeshuri babo' 
                    : 'To help teachers monitor and support their students\' progress'
                  }
                </li>
                <li>
                  {currentLanguage === 'rw' 
                    ? 'Guhanga amakuru y\'intambwe ku babyeyi' 
                    : 'To provide progress updates to parents/guardians'
                  }
                </li>
                <li>
                  {currentLanguage === 'rw' 
                    ? 'Gukoresha amakuru mu nzira y\'uburezi kugira ngo dushobore guhindura serivisi zacu' 
                    : 'To analyze usage patterns to improve our educational services'
                  }
                </li>
              </ul>
            </div>

            <div className="legal-list">
              <h3>
                {currentLanguage === 'rw' 
                  ? 'Ubwoba n\'Ukuvugurura:' 
                  : 'Safety and Security:'
                }
              </h3>
              <ul>
                <li>
                  {currentLanguage === 'rw' 
                    ? 'Kurengera abana mu nzira y\'ubwoba kandi gukoresha amakuru y\'abana gusa mu nzira y\'uburezi' 
                    : 'To protect children from harm and ensure age-appropriate content'
                  }
                </li>
                <li>
                  {currentLanguage === 'rw' 
                    ? 'Gukurikira ubukoresha kugira ngo dushobore gukoresha amakuru y\'abana gusa mu nzira y\'uburezi' 
                    : 'To monitor platform usage to prevent misuse'
                  }
                </li>
                <li>
                  {currentLanguage === 'rw' 
                    ? 'Gukoresha amakuru y\'abana gusa mu nzira y\'uburezi kandi gukoresha amakuru y\'abana gusa mu nzira y\'uburezi' 
                    : 'To detect and prevent unauthorized access or security threats'
                  }
                </li>
                <li>
                  {currentLanguage === 'rw' 
                    ? 'Gukoresha amakuru y\'abana gusa mu nzira y\'uburezi kandi gukoresha amakuru y\'abana gusa mu nzira y\'uburezi' 
                    : 'To comply with legal obligations and protect user rights'
                  }
                </li>
              </ul>
            </div>

            <div className="legal-list">
              <h3>
                {currentLanguage === 'rw' 
                  ? 'Guhagararira:' 
                  : 'Communication:'
                }
              </h3>
              <ul>
                <li>
                  {currentLanguage === 'rw' 
                    ? 'Guhagararira abarezi ku makuru y\'ubukoresha n\'intambwe' 
                    : 'To communicate with teachers about platform updates and student progress'
                  }
                </li>
                <li>
                  {currentLanguage === 'rw' 
                    ? 'Guhagararira ababyeyi ku makuru y\'intambwe y\'abana babo' 
                    : 'To send progress reports to parents/guardians'
                  }
                </li>
                <li>
                  {currentLanguage === 'rw' 
                    ? 'Guhagararira abakoresha ku makuru y\'ubukoresha n\'intambwe' 
                    : 'To respond to user inquiries and provide support'
                  }
                </li>
                <li>
                  {currentLanguage === 'rw' 
                    ? 'Guhagararira abakoresha ku makuru y\'ubukoresha n\'intambwe (mu nzira y\'uburezi gusa)' 
                    : 'To send important notifications about account or safety matters (educational purposes only)'
                  }
                </li>
              </ul>
            </div>
          </section>

          {/* Child Safety and Protection */}
          <section className="legal-section">
            <h2>
              {currentLanguage === 'rw' 
                ? '4. Ubwoba bw\'Abana n\'Ukuvugurura' 
                : '4. Child Safety and Protection'
              }
            </h2>
            <div className="legal-highlight">
              <h4>
                {currentLanguage === 'rw' 
                  ? 'Ubwoba bw\'Abana ni Intego yacu y\'Ibanze:' 
                  : 'Child Safety is Our Top Priority:'
                }
              </h4>
              <p>
                {currentLanguage === 'rw' 
                  ? 'Ubwoba n\'ubwoba bw\'abana ni intego yacu y\'ibanze. Dukoresha amakuru y\'abana gusa mu nzira y\'uburezi. Dukoresha amakuru y\'abana gusa mu nzira y\'uburezi kandi dukoresha amakuru y\'abana gusa mu nzira y\'uburezi.' 
                  : 'The safety and well-being of children is our highest priority. We have implemented comprehensive safety measures, strict content moderation, and age-appropriate design principles. All content is reviewed to ensure it is educational and safe for children.'
                }
              </p>
            </div>

            <div className="legal-list">
              <h3>
                {currentLanguage === 'rw' 
                  ? 'Ingamba z\'Ubwoba:' 
                  : 'Safety Measures:'
                }
              </h3>
              <ul>
                <li>
                  {currentLanguage === 'rw' 
                    ? 'Ibyiciro byose ni by\'uburezi kandi bihuje n\'ubwoba bw\'abana' 
                    : 'All content is educational and age-appropriate for primary school students'
                  }
                </li>
                <li>
                  {currentLanguage === 'rw' 
                    ? 'Gukurikira ubukoresha kugira ngo dushobore gukoresha amakuru y\'abana gusa mu nzira y\'uburezi' 
                    : 'Strict monitoring of all user interactions and content'
                  }
                </li>
                <li>
                  {currentLanguage === 'rw' 
                    ? 'Ubwoba bw\'ababyeyi n\'abarezi kugira ngo dushobore gukoresha amakuru y\'abana gusa mu nzira y\'uburezi' 
                    : 'Parental and teacher oversight features for student accounts'
                  }
                </li>
                <li>
                  {currentLanguage === 'rw' 
                    ? 'Gukoresha amakuru y\'abana gusa mu nzira y\'uburezi kandi gukoresha amakuru y\'abana gusa mu nzira y\'uburezi' 
                    : 'Regular safety audits and content reviews by educational experts'
                  }
                </li>
                <li>
                  {currentLanguage === 'rw' 
                    ? 'Sisitemu y\'ubwoba kugira ngo dushobore gukoresha amakuru y\'abana gusa mu nzira y\'uburezi' 
                    : 'Immediate reporting system for any safety concerns or inappropriate content'
                  }
                </li>
                <li>
                  {currentLanguage === 'rw' 
                    ? 'Gukoresha amakuru y\'abana gusa mu nzira y\'uburezi kandi gukoresha amakuru y\'abana gusa mu nzira y\'uburezi' 
                    : 'No direct messaging between students without teacher supervision'
                  }
                </li>
                <li>
                  {currentLanguage === 'rw' 
                    ? 'Gukoresha amakuru y\'abana gusa mu nzira y\'uburezi kandi gukoresha amakuru y\'abana gusa mu nzira y\'uburezi' 
                    : 'Age-appropriate gamification that encourages learning without external social features'
                  }
                </li>
              </ul>
            </div>

            <div className="legal-list">
              <h3>
                {currentLanguage === 'rw' 
                  ? 'Ibyiciro by\'Uburezi:' 
                  : 'Educational Content Standards:'
                }
              </h3>
              <ul>
                <li>
                  {currentLanguage === 'rw' 
                    ? 'Ibyiciro byose byagenewe uburezi gusa' 
                    : 'All content is designed for educational purposes only'
                  }
                </li>
                <li>
                  {currentLanguage === 'rw' 
                    ? 'Nta makuru y\'ubucuruzi cyangwa amakuru y\'abana' 
                    : 'No advertising or commercial content targeted at children'
                  }
                </li>
                <li>
                  {currentLanguage === 'rw' 
                    ? 'Ibyiciro byose bihuje n\'urwego rw\'ishuli n\'ubwoba bw\'abana' 
                    : 'Content is aligned with Rwandan primary school curriculum standards'
                  }
                </li>
                <li>
                  {currentLanguage === 'rw' 
                    ? 'Gukoresha amakuru y\'abana gusa mu nzira y\'uburezi kandi gukoresha amakuru y\'abana gusa mu nzira y\'uburezi' 
                    : 'Multilingual support (English and Kinyarwanda) for inclusive learning'
                  }
                </li>
              </ul>
            </div>
          </section>

          {/* Data Security */}
          <section className="legal-section">
            <h2>
              {currentLanguage === 'rw' 
                ? '5. Ukuvugurura Amakuru' 
                : '5. Data Security'
              }
            </h2>
            <p>
              {currentLanguage === 'rw' 
                ? 'Dukoresha ingamba z\'ubwoba z\'ibanze kugira ngo dukinge amakuru y\'abakoresha. Dukoresha amakuru y\'abana gusa mu nzira y\'uburezi kandi dukoresha amakuru y\'abana gusa mu nzira y\'uburezi.' 
                : 'We implement industry-standard security measures to protect all user data. We use encryption, secure authentication, and regular security audits to ensure data protection.'
              }
            </p>
            
            <div className="legal-list">
              <h3>
                {currentLanguage === 'rw' 
                  ? 'Ingamba z\'Ukuvugurura:' 
                  : 'Security Measures:'
                }
              </h3>
              <ul>
                <li>
                  {currentLanguage === 'rw' 
                    ? 'Gukoresha amakuru y\'abana gusa mu nzira y\'uburezi (SSL/TLS) kugira ngo dukinge amakuru mu nzira y\'uburezi' 
                    : 'Encrypted data transmission (SSL/TLS) to protect data in transit'
                  }
                </li>
                <li>
                  {currentLanguage === 'rw' 
                    ? 'Gukoresha amakuru y\'abana gusa mu nzira y\'uburezi kandi gukoresha amakuru y\'abana gusa mu nzira y\'uburezi' 
                    : 'Encrypted data storage to protect data at rest'
                  }
                </li>
                <li>
                  {currentLanguage === 'rw' 
                    ? 'Gukoresha amakuru y\'abana gusa mu nzira y\'uburezi (bcrypt) kugira ngo dukinge amakuru y\'abana' 
                    : 'Secure password hashing (bcrypt) to protect user credentials'
                  }
                </li>
                <li>
                  {currentLanguage === 'rw' 
                    ? 'Gukoresha amakuru y\'abana gusa mu nzira y\'uburezi kandi gukoresha amakuru y\'abana gusa mu nzira y\'uburezi' 
                    : 'Regular security updates and vulnerability assessments'
                  }
                </li>
                <li>
                  {currentLanguage === 'rw' 
                    ? 'Gukoresha amakuru y\'abana gusa mu nzira y\'uburezi kandi gukoresha amakuru y\'abana gusa mu nzira y\'uburezi' 
                    : 'Limited access controls - only authorized personnel can access user data'
                  }
                </li>
                <li>
                  {currentLanguage === 'rw' 
                    ? 'Gukoresha amakuru y\'abana gusa mu nzira y\'uburezi kandi gukoresha amakuru y\'abana gusa mu nzira y\'uburezi' 
                    : 'Secure authentication using JWT tokens with expiration'
                  }
                </li>
                <li>
                  {currentLanguage === 'rw' 
                    ? 'Gukoresha amakuru y\'abana gusa mu nzira y\'uburezi kandi gukoresha amakuru y\'abana gusa mu nzira y\'uburezi' 
                    : 'Regular backups to prevent data loss'
                  }
                </li>
              </ul>
            </div>
          </section>

          {/* Information Sharing */}
          <section className="legal-section">
            <h2>
              {currentLanguage === 'rw' 
                ? '6. Gushyiraho Amakuru' 
                : '6. Information Sharing'
              }
            </h2>
            <p>
              {currentLanguage === 'rw' 
                ? 'Ntidugurisha, ntidugurisha, cyangwa ngo dushyire hamwe amakuru y\'abantu n\'abandi bantu, usibye mu byiciro by\'ibanze byanditse aha. Dukoresha amakuru y\'abana gusa mu nzira y\'uburezi.' 
                : 'We do not sell, trade, or share personal information with third parties, except in the specific circumstances outlined below. We never share children\'s information for commercial purposes.'
              }
            </p>
            
            <div className="legal-list">
              <h3>
                {currentLanguage === 'rw' 
                  ? 'Gushyiraho mu Nzira y\'Uburezi:' 
                  : 'Educational Sharing:'
                }
              </h3>
              <ul>
                <li>
                  {currentLanguage === 'rw' 
                    ? 'Ku babyeyi/abarinzi kugira ngo babashe gukurikira intambwe y\'abana babo' 
                    : 'With parents/guardians to allow them to monitor their children\'s progress'
                  }
                </li>
                <li>
                  {currentLanguage === 'rw' 
                    ? 'Ku barezi kugira ngo babashe gufasha abanyeshuri babo' 
                    : 'With teachers to enable them to support their students'
                  }
                </li>
                <li>
                  {currentLanguage === 'rw' 
                    ? 'Mu nzira y\'uburezi gusa - amakuru y\'intambwe n\'ubukoresha' 
                    : 'Educational purposes only - progress and usage data for learning improvement'
                  }
                </li>
              </ul>
            </div>

            <div className="legal-list">
              <h3>
                {currentLanguage === 'rw' 
                  ? 'Gushyiraho mu Nzira y\'Amategeko:' 
                  : 'Legal Requirements:'
                }
              </h3>
              <ul>
                <li>
                  {currentLanguage === 'rw' 
                    ? 'Niba byagenwe n\'amategeko cyangwa amabwiriza' 
                    : 'If required by law or legal process'
                  }
                </li>
                <li>
                  {currentLanguage === 'rw' 
                    ? 'Kugira ngo dukinge ubwoba bw\'abana cyangwa abakoresha' 
                    : 'To protect the safety of children or users'
                  }
                </li>
                <li>
                  {currentLanguage === 'rw' 
                    ? 'Kugira ngo dukinge uburenganzira bwacu cyangwa ubw\'abandi' 
                    : 'To protect our rights or the rights of others'
                  }
                </li>
                <li>
                  {currentLanguage === 'rw' 
                    ? 'Mu nzira y\'uburezi gusa - amakuru y\'intambwe n\'ubukoresha' 
                    : 'In response to valid legal requests from authorities'
                  }
                </li>
              </ul>
            </div>

            <div className="legal-highlight">
              <h4>
                {currentLanguage === 'rw' 
                  ? 'Ntidushyiraho Amakuru y\'Abana mu Nzira y\'Ubucuruzi:' 
                  : 'We Never Share Children\'s Information for Commercial Purposes:'
                }
              </h4>
              <p>
                {currentLanguage === 'rw' 
                  ? 'Ntidugurisha, ntidugurisha, cyangwa ngo dushyire hamwe amakuru y\'abana n\'abandi bantu mu nzira y\'ubucuruzi. Dukoresha amakuru y\'abana gusa mu nzira y\'uburezi.' 
                  : 'We never sell, trade, or share children\'s information with advertisers, marketers, or any commercial third parties. Children\'s data is used exclusively for educational purposes.'
                }
              </p>
            </div>
          </section>

          {/* Parental Rights */}
          <section className="legal-section">
            <h2>
              {currentLanguage === 'rw' 
                ? '7. Uburenganzira bw\'Ababyeyi' 
                : '7. Parental Rights'
              }
            </h2>
            <p>
              {currentLanguage === 'rw' 
                ? 'Ababyeyi n\'abarinzi bafite uburenganzira bwo gukurikira, guhindura, cyangwa gukuraho amakuru y\'abana babo. Dukoresha amakuru y\'abana gusa mu nzira y\'uburezi.' 
                : 'Parents and guardians have specific rights regarding their children\'s information. We respect these rights and provide tools for parents to exercise them.'
              }
            </p>
            
            <div className="legal-list">
              <h3>
                {currentLanguage === 'rw' 
                  ? 'Uburenganzira bw\'Ababyeyi:' 
                  : 'Parental Rights:'
                }
              </h3>
              <ul>
                <li>
                  {currentLanguage === 'rw' 
                    ? 'Kugira uburenganzira bwo gukurikira amakuru y\'intambwe y\'umwana' 
                    : 'Right to access their child\'s learning progress and data'
                  }
                </li>
                <li>
                  {currentLanguage === 'rw' 
                    ? 'Kugira uburenganzira bwo guhindura amakuru y\'umwana' 
                    : 'Right to correct inaccurate information about their child'
                  }
                </li>
                <li>
                  {currentLanguage === 'rw' 
                    ? 'Kugira uburenganzira bwo gukuraho amakuru y\'umwana' 
                    : 'Right to request deletion of their child\'s information'
                  }
                </li>
                <li>
                  {currentLanguage === 'rw' 
                    ? 'Kugira uburenganzira bwo gukuraho amakuru y\'umwana' 
                    : 'Right to withdraw consent for data collection'
                  }
                </li>
                <li>
                  {currentLanguage === 'rw' 
                    ? 'Kugira uburenganzira bwo gukurikira amakuru y\'intambwe y\'umwana' 
                    : 'Right to receive notifications about data breaches affecting their child'
                  }
                </li>
                <li>
                  {currentLanguage === 'rw' 
                    ? 'Kugira uburenganzira bwo gukurikira amakuru y\'intambwe y\'umwana' 
                    : 'Right to object to certain data processing activities'
                  }
                </li>
              </ul>
            </div>

            <div className="legal-list">
              <h3>
                {currentLanguage === 'rw' 
                  ? 'Uko Mwakoresha Uburenganzira bwawe:' 
                  : 'How to Exercise Your Rights:'
                }
              </h3>
              <ul>
                <li>
                  {currentLanguage === 'rw' 
                    ? 'Twandikire ku privacy@diglearners.rw' 
                    : 'Contact us at privacy@diglearners.rw'
                  }
                </li>
                <li>
                  {currentLanguage === 'rw' 
                    ? 'Tugomba guhagararira mu gihe cy\'iminsi 30' 
                    : 'We will respond within 30 days'
                  }
                </li>
                <li>
                  {currentLanguage === 'rw' 
                    ? 'Tugomba guhagararira mu nzira y\'uburezi kandi dukoresha amakuru y\'abana gusa mu nzira y\'uburezi' 
                    : 'We may require verification of your identity as the parent/guardian'
                  }
                </li>
                <li>
                  {currentLanguage === 'rw' 
                    ? 'Ntacyo mwakwiriye kwishyura kugira ngo mukoreshe uburenganzira bwawe' 
                    : 'There is no charge for exercising your rights'
                  }
                </li>
              </ul>
            </div>
          </section>

          {/* Data Retention */}
          <section className="legal-section">
            <h2>
              {currentLanguage === 'rw' 
                ? '8. Gukomeza Amakuru' 
                : '8. Data Retention'
              }
            </h2>
            <p>
              {currentLanguage === 'rw' 
                ? 'Dukomeza amakuru y\'abanyeshuri gusa igihe gikwiye kugira ngo dushobore guha serivisi z\'uburezi. Dukoresha amakuru y\'abana gusa mu nzira y\'uburezi.' 
                : 'We retain student data only as long as necessary for educational purposes. Once data is no longer needed, we securely delete it.'
              }
            </p>
            
            <div className="legal-list">
              <h3>
                {currentLanguage === 'rw' 
                  ? 'Igihe cyo Gukomeza:' 
                  : 'Retention Periods:'
                }
              </h3>
              <ul>
                <li>
                  {currentLanguage === 'rw' 
                    ? 'Amakuru y\'abanyeshuri bakoresha: Kugeza abanyeshuri bavuye cyangwa bavuye mu ishuli' 
                    : 'Active student data: Until student graduates or withdraws from school'
                  }
                </li>
                <li>
                  {currentLanguage === 'rw' 
                    ? 'Amakuru y\'abanyeshuri batakoresha: Igihe cy\'imyaka 2 gusa' 
                    : 'Inactive student accounts: Maximum 2 years after last activity'
                  }
                </li>
                <li>
                  {currentLanguage === 'rw' 
                    ? 'Amakuru y\'ubwoba: Nk\'uko byagenwe n\'amategeko' 
                    : 'Safety records: As required by law (may be longer for legal compliance)'
                  }
                </li>
                <li>
                  {currentLanguage === 'rw' 
                    ? 'Amakuru y\'ubwoba (y\'abana gusa): Igihe gito gusa kugira ngo dushobore guhindura serivisi' 
                    : 'Anonymous analytics data: Indefinitely for research and service improvement (no personal identifiers)'
                  }
                </li>
                <li>
                  {currentLanguage === 'rw' 
                    ? 'Amakuru y\'abarezi: Kugeza barezi bavuye cyangwa bavuye mu ishuli' 
                    : 'Teacher data: Until teacher account is closed or teacher leaves the school'
                  }
                </li>
              </ul>
            </div>

            <div className="legal-list">
              <h3>
                {currentLanguage === 'rw' 
                  ? 'Gukuraho Amakuru:' 
                  : 'Data Deletion:'
                }
              </h3>
              <ul>
                <li>
                  {currentLanguage === 'rw' 
                    ? 'Dukuraho amakuru y\'abana mu nzira y\'uburezi kandi dukoresha amakuru y\'abana gusa mu nzira y\'uburezi' 
                    : 'Data is securely deleted using industry-standard methods'
                  }
                </li>
                <li>
                  {currentLanguage === 'rw' 
                    ? 'Dukuraho amakuru y\'abana mu nzira y\'uburezi kandi dukoresha amakuru y\'abana gusa mu nzira y\'uburezi' 
                    : 'Backup copies are also deleted within the retention period'
                  }
                </li>
                <li>
                  {currentLanguage === 'rw' 
                    ? 'Dukuraho amakuru y\'abana mu nzira y\'uburezi kandi dukoresha amakuru y\'abana gusa mu nzira y\'uburezi' 
                    : 'Some data may be retained longer if required by law or for safety purposes'
                  }
                </li>
              </ul>
            </div>
          </section>

          {/* Cookies and Tracking */}
          <section className="legal-section">
            <h2>
              {currentLanguage === 'rw' 
                ? '9. Amakuki n\'Ubukoresha' 
                : '9. Cookies and Tracking'
              }
            </h2>
            <p>
              {currentLanguage === 'rw' 
                ? 'Dukoresha amakuki make gusa kugira ngo serivisi zacu zikore. Dukoresha amakuru y\'abana gusa mu nzira y\'uburezi. Ntidukoresha amakuki y\'ubucuruzi cyangwa amakuki y\'abana.' 
                : 'We use minimal cookies and tracking technologies, only what is necessary for platform functionality. We do not use advertising cookies or commercial tracking. All tracking is for educational purposes only.'
              }
            </p>
            
            <div className="legal-list">
              <h3>
                {currentLanguage === 'rw' 
                  ? 'Uko Dukoresha Amakuki:' 
                  : 'How We Use Cookies:'
                }
              </h3>
              <ul>
                <li>
                  {currentLanguage === 'rw' 
                    ? 'Amakuki y\'ibanze: Kugira ngo serivisi zikore (kwinjira, gukomeza kwinjira)' 
                    : 'Essential cookies: Required for platform functionality (login, session management)'
                  }
                </li>
                <li>
                  {currentLanguage === 'rw' 
                    ? 'Gukurikira intambwe: Kugira ngo dushobore gukurikira intambwe y\'abanyeshuri' 
                    : 'Progress tracking: To track student learning progress and achievements'
                  }
                </li>
                <li>
                  {currentLanguage === 'rw' 
                    ? 'Gukurikira ubukoresha: Kugira ngo dushobore guhindura serivisi zacu' 
                    : 'Usage analytics: To improve our services (anonymous, aggregated data only)'
                  }
                </li>
                <li>
                  {currentLanguage === 'rw' 
                    ? 'Nta makuki y\'ubucuruzi: Ntidukoresha amakuki y\'ubucuruzi cyangwa amakuki y\'abana' 
                    : 'No advertising cookies: We do not use cookies for advertising or marketing'
                  }
                </li>
                <li>
                  {currentLanguage === 'rw' 
                    ? 'Uburenganzira bw\'ababyeyi: Ababyeyi bafite uburenganzira bwo gukuraho amakuki' 
                    : 'Parental control: Parents can manage cookie preferences through browser settings'
                  }
                </li>
              </ul>
            </div>

            <p>
              {currentLanguage === 'rw' 
                ? 'Reba Politiki yacu y\'Amakuki kugira ngo ubashe ubwoba bwose ku makuki n\'ubukoresha.' 
                : 'Please see our Cookies Policy for complete details about cookies and tracking technologies.'
              }
            </p>
          </section>

          {/* International Data Transfers */}
          <section className="legal-section">
            <h2>
              {currentLanguage === 'rw' 
                ? '10. Gushyiraho Amakuru mu Bindi Bihugu' 
                : '10. International Data Transfers'
              }
            </h2>
            <p>
              {currentLanguage === 'rw' 
                ? 'Dukomeza amakuru y\'abanyeshuri mu Rwanda gusa, usibye niba byagenwe n\'amategeko. Dukoresha amakuru y\'abana gusa mu nzira y\'uburezi.' 
                : 'We prioritize keeping student data within Rwanda. Data is primarily stored and processed in Rwanda. If data must be transferred internationally (e.g., for cloud hosting), we ensure appropriate safeguards are in place.'
              }
            </p>
            
            <div className="legal-list">
              <h3>
                {currentLanguage === 'rw' 
                  ? 'Ingamba z\'Ukuvugurura:' 
                  : 'Safeguards:'
                }
              </h3>
              <ul>
                <li>
                  {currentLanguage === 'rw' 
                    ? 'Dukoresha amakuru y\'abana gusa mu nzira y\'uburezi kandi dukoresha amakuru y\'abana gusa mu nzira y\'uburezi' 
                    : 'Data encryption during transfer and storage'
                  }
                </li>
                <li>
                  {currentLanguage === 'rw' 
                    ? 'Dukoresha amakuru y\'abana gusa mu nzira y\'uburezi kandi dukoresha amakuru y\'abana gusa mu nzira y\'uburezi' 
                    : 'Contractual agreements with service providers requiring data protection'
                  }
                </li>
                <li>
                  {currentLanguage === 'rw' 
                    ? 'Dukoresha amakuru y\'abana gusa mu nzira y\'uburezi kandi dukoresha amakuru y\'abana gusa mu nzira y\'uburezi' 
                    : 'Regular audits of data processing activities'
                  }
                </li>
              </ul>
            </div>
          </section>

          {/* Changes to Privacy Policy */}
          <section className="legal-section">
            <h2>
              {currentLanguage === 'rw' 
                ? '11. Guhindura Politiki y\'Ubwigenge' 
                : '11. Changes to Privacy Policy'
              }
            </h2>
            <p>
              {currentLanguage === 'rw' 
                ? 'Dushobora guhindura politiki yacu y\'ubwigenge igihe cyose. Tugomba guhagararira abakoresha ku makuru y\'ubukoresha n\'intambwe. Dukoresha amakuru y\'abana gusa mu nzira y\'uburezi.' 
                : 'We may update this Privacy Policy from time to time to reflect changes in our practices or legal requirements. We will notify users of significant changes through email or platform notifications. Continued use of our services after changes constitutes acceptance of the updated policy.'
              }
            </p>
            <p>
              {currentLanguage === 'rw' 
                ? 'Itangazo ryose rigomba gukorwa mu nzira y\'uburezi kandi dukoresha amakuru y\'abana gusa mu nzira y\'uburezi.' 
                : 'All notifications will be sent in advance, and parents will be notified of any changes affecting children\'s data.'
              }
            </p>
          </section>

          {/* Contact Information */}
          <section className="legal-section">
            <h2>
              {currentLanguage === 'rw' 
                ? '12. Amakuru y\'Ubufasha' 
                : '12. Contact Information'
              }
            </h2>
            <p>
              {currentLanguage === 'rw' 
                ? 'Niba mufite ibibazo, ibitekerezo, cyangwa ibitekerezo ku politiki yacu y\'ubwigenge, nyamuneka mutwandikire:' 
                : 'If you have questions, concerns, or requests regarding our Privacy Policy or your personal information, please contact us:'
              }
            </p>
            <div className="contact-info">
              <p>
                <strong>
                  {currentLanguage === 'rw' 
                    ? 'DigLearners - Ubwoba bw\'Ubwigenge' 
                    : 'DigLearners - Privacy Team'
                  }
                </strong>
              </p>
              <p>
                {currentLanguage === 'rw' 
                  ? 'Kigali, Rwanda' 
                  : 'Kigali, Rwanda'
                }
              </p>
              <p>
                {currentLanguage === 'rw' 
                  ? 'Imeli: privacy@diglearners.rw' 
                  : 'Email: privacy@diglearners.rw'
                }
              </p>
              <p>
                {currentLanguage === 'rw' 
                  ? 'Telefone: +250 788 123 456' 
                  : 'Phone: +250 788 123 456'
                }
              </p>
              <p>
                {currentLanguage === 'rw' 
                  ? 'Igihe cyo guhagararira: Iminsi 30' 
                  : 'Response time: Within 30 days'
                }
              </p>
            </div>
          </section>

          {/* Ethical Commitment */}
          <section className="legal-section ethical-commitment">
            <h2>
              {currentLanguage === 'rw' 
                ? '13. Icyemezo cy\'Ubwoba' 
                : '13. Ethical Commitment'
              }
            </h2>
            <p>
              {currentLanguage === 'rw' 
                ? 'DigLearners yiyemeje kurengera ubwigenge n\'ubwoba bw\'abana. Dukoresha amakuru y\'abana gusa mu nzira y\'uburezi. Dukoresha amakuru y\'abana gusa mu nzira y\'uburezi.' 
                : 'DigLearners is committed to protecting privacy and promoting child safety. We believe that children\'s data should be used only for educational purposes and never for commercial gain.'
              }
            </p>
            <div className="ethical-principles">
              <div className="ethical-principle">
                <h3>
                  {currentLanguage === 'rw' 
                    ? 'Gutanga Abana Intego' 
                    : 'Child-Centric Design'
                  }
                </h3>
                <p>
                  {currentLanguage === 'rw' 
                    ? 'Ibyiciro byose byagenewe kugira ngo abana babashe kwiga mu nzira y\'ubwoba. Dukoresha amakuru y\'abana gusa mu nzira y\'uburezi.' 
                    : 'Every decision we make prioritizes the safety, privacy, and well-being of children. Our platform is designed with children\'s best interests at heart.'
                  }
                </p>
              </div>
              <div className="ethical-principle">
                <h3>
                  {currentLanguage === 'rw' 
                    ? 'Gusobanura' 
                    : 'Transparency'
                  }
                </h3>
                <p>
                  {currentLanguage === 'rw' 
                    ? 'Dusobanura uko dukoresha amakuru y\'abana. Dukoresha amakuru y\'abana gusa mu nzira y\'uburezi. Dukoresha amakuru y\'abana gusa mu nzira y\'uburezi.' 
                    : 'We are transparent about our data practices and provide clear, understandable information to parents and students. We believe in open communication and informed consent.'
                  }
                </p>
              </div>
              <div className="ethical-principle">
                <h3>
                  {currentLanguage === 'rw' 
                    ? 'Gukusanya Amakuru Make' 
                    : 'Minimal Data Collection'
                  }
                </h3>
                <p>
                  {currentLanguage === 'rw' 
                    ? 'Dukusanya amakuru make gusa kugira ngo dushobore guha serivisi z\'uburezi. Dukoresha amakuru y\'abana gusa mu nzira y\'uburezi.' 
                    : 'We collect only the minimum data necessary for educational purposes and child safety. We do not collect unnecessary information, and we delete data when it is no longer needed.'
                  }
                </p>
              </div>
              <div className="ethical-principle">
                <h3>
                  {currentLanguage === 'rw' 
                    ? 'Ubwoba bw\'Abana' 
                    : 'Child Safety First'
                  }
                </h3>
                <p>
                  {currentLanguage === 'rw' 
                    ? 'Ubwoba bw\'abana ni intego yacu y\'ibanze. Dukoresha amakuru y\'abana gusa mu nzira y\'uburezi. Dukoresha amakuru y\'abana gusa mu nzira y\'uburezi.' 
                    : 'Child safety is our top priority. We implement comprehensive safety measures, content moderation, and age-appropriate design to protect children online.'
                  }
                </p>
              </div>
            </div>
          </section>
        </div>
      </div>
      <PublicFooter />
    </div>
  );
};

export default PrivacyPolicy;
